apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dj
spec:
  scaleTargetRef:
    name:          dj
  minReplicaCount: 1        # Optional. Default: 0
  maxReplicaCount: 10       # Optional. Default: 100
  triggers:
    - type: prometheus
      metadata:
        serverAddress: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-ee9943e2-065d-426d-9b78-9f0ff0af398d
        metricName: adot_envoy_cluster_upstream_rq_total
        threshold: '1'
        # Note: query must return a vector/scalar single element response
        query: sum(rate(adot_envoy_cluster_upstream_rq_total{app="dj"}[2m]))
